spring:
  application:
     name: Config-Dev
eureka:
  instance:
    prefer-ip-address: true
  client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        default-zone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
